#!/bin/sh


wget  --retry-connrefused -q --read-timeout=120 --tries=inf --no-verbose -O- http://github.com/Ae3NerdGod/PINNg/releases/download/twist-os-1.4.1/rootfs_part1 |cat && wget  --retry-connrefused -q --read-timeout=120 --tries=inf --no-verbose -O- http://github.com/Ae3NerdGod/PINNg/releases/download/twist-os-1.4.1/rootfs_part2 |cat 


